name: moneytracker

description: "A minimalistic money tracking Flutter app with a black-and-white theme."

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
